
export const RAFFLES = [
    {
        mint: "Gj8q7FboqyEGkJy7oYDFWjrozgsGegjkHnbLtZr9LvUW",
        raffleKey: "Gj8q7FboqyEGkJy7oYDFWjrozgsGegjkHnbLtZr9LvUW",
        collection: "The Heist",
        name: "The Heist #10326",
        price: 0.2,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://arweave.net/qjLAZ53d2hkKkJZmKQp3A3TwtRDWOrm6oIXQQDt9WaE",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-10").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 50,
        purchasedTickets: 33,
        verified: true
    },
    {
        mint: "4NoWtSSfPFvrCm9Vv9hifJM7MbztXRK8zP9QWikrgSYo",
        raffleKey: "89Xwuah6o9Y2q91EREgsc1wKeFHYyfXEZKqPFRBNrfhv",
        collection: "The Heist",
        name: "The Heist #10326",
        price: 0.2,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https%3A%2F%2Farweave.net%2F8JCFe3-S-RS6Gw1E5PzW2i_NKfzYGDYt8Oin5BbWPaE%3Fext%3Dpng",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-12").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 99,
        purchasedTickets: 60,
        verified: false
    },
    {
        mint: "C35rURD6kLSjjevDrXAvG484g54rKzCZ97QrX9Y6fDHj",
        raffleKey: "J1S9H3QjnRtBbbuD4HjPV6RpRhwuk4zKbxsnCHuTgh9w",
        collection: "Mad Lads",
        name: "Mad Lads #103",
        price: 4,
        token: "SOLAPE",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://madlads.s3.us-west-2.amazonaws.com/images/2318.png",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-7").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 99,
        purchasedTickets: 60,
        verified: true
    },
    {
        mint: "2uNXegkz5NnULdhziyMGpACd3ySf9TKLFjfVqqeQb2Sb",
        raffleKey: "7thDNBn8JRetPm6mWxEM3RqeaaXLgFSQ2TUmT13FQ2H1",
        collection: "Solcasino.io",
        name: "Solcasino.io #3874",
        price: 4,
        token: "SOLAPE",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fill:400:400:0:0/plain/https://cdn45.solcasino.io/collection/3874.png",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-8").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 99,
        purchasedTickets: 60,
        verified: true
    },
    {
        mint: "FGQh9VkcPnvhEiBicwRPDjf1NCc7GYpLbGxcgAyc9WhG",
        raffleKey: "BUjZjAS2vbbb65g7Z1Ca9ZRVYoJscURG5L3AkVvHP9ac",
        collection: "Famous Fox Federation",
        name: "Fox #7128",
        price: 40,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://famousfoxes.com/hd/7128.png",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-7").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 200,
        purchasedTickets: 88,
        verified: true
    },
    {
        mint: "3HEtZRZC9LZCkhAAnJymVo21f3U9CB73GLCUhS3ZA88q",
        raffleKey: "SMBtHCCC6RYRutFEPb4gZqeBLUZbMNhRKaMKZZLHi7W",
        collection: "SMB Gen2",
        name: "SMB #2308",
        price: 0.5,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://arweave.net/fjk6ELmQ_OzBXqohGouRboP1Yo0_k4PP8G87-ZL_CEw",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-7").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 200,
        purchasedTickets: 88,
        verified: true
    },
    {
        mint: "2kuDG8pBLxowG3bLPdgDhWdK135o9BrYdty4NRvdLfTP",
        raffleKey: "SMBtHCCC6RYRutFEPb4gZqeBLUZbMNhRKaMKZZLHi7W",
        collection: "SMB Gen2",
        name: "SMB #234",
        price: 0.4,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://arweave.net/QSPFBSGrVFRyao4vJahhaKbsiEy1Uw3nn0yng5VUPFs",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-7").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 200,
        purchasedTickets: 88,
        verified: true
    },
    {
        mint: "GEcZ2vsHJApcBJnohEnF7UTKKfxayvVpQr8ShGFKWAQR",
        raffleKey: "Cwv98ALbKdbtNmycUgK6K4ENr43wCW8VqvJAKAKdPKEu",
        collection: "AInimatez",
        name: "AInimatez 27",
        price: 0.5,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://arweave.net/4uKtT3imsF1UqHqVgkuYUrwuIOdcDpnpu3sNdvL3iWs",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-8").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 333,
        purchasedTickets: 222,
        verified: true
    },
    {
        mint: "GBmUmGw3B5MYf8rV14hEfZ3LVP4nCFCP9ifUnwmbYGC7",
        raffleKey: "J1S9H3QjnRtBbbuD4HjPV6RpRhwuk4zKbxsnCHuTgh9w",
        collection: "Mad Lads",
        name: "Mad Lads #9180",
        price: 0.5,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://madlads.s3.us-west-2.amazonaws.com/images/9180.png",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-10").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 333,
        purchasedTickets: 222,
        verified: true
    },
    {
        mint: "4r4CNCQefvb2tvSKtxQPVFHYsTZqRW3uAginwuDznVRA",
        raffleKey: "J1S9H3QjnRtBbbuD4HjPV6RpRhwuk4zKbxsnCHuTgh1w",
        collection: "Mad Lads",
        name: "Mad Lads #9180",
        price: 0.5,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://madlads.s3.us-west-2.amazonaws.com/images/768.png",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-10").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 333,
        purchasedTickets: 222,
        verified: true
    },
    {
        mint: "FAHLLxhmuEcdn1KkiJtpZM8UjJBKUHSrGVWM3P8mvMCe",
        raffleKey: "J1S9H3QjnRtBbbuD4HjPV6RpRhwuk4zKbxsnCHuTgh1w",
        collection: "Mad Lads",
        name: "Degen Ape #2575",
        price: 20,
        token: "SOLAPE",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://arweave.net/1-r-5r9QdnJI-8Qnzxsr2DQitaHk6gU_GrbVfudYZMI",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-7").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 333,
        purchasedTickets: 222,
        verified: true
    },
    {
        mint: "BNdNcM3JsqGFB8H7E7uXvRAGTGxZucm5HJzWT98vGUFn",
        raffleKey: "DSwfRF1jhhu6HpSuzaig1G19kzP73PfLZBPLofkw6fL1",
        collection: "Degenerate Ape Academy",
        name: "Degen Ape #1885",
        price: 0.5,
        token: "SOL",
        tokenDecimal: 9,
        image: "https://img-cdn.magiceden.dev/rs:fit:640:640:0:0/plain/https://arweave.net/391Q6-wBVdWTktCsdXyXubEMpEh-ewrUhUNX093XVd0",
        creator: "9kh6LptSFU4RmKx5no5nSjKs8NG1y1MU5nMyWbU82HwV",
        endTimeStamp: new Date("2023-7-10").getTime(),
        createdTimeStamp: new Date("2023-7-4").getTime(),
        totalTickets: 333,
        purchasedTickets: 222,
        verified: true
    }
]